<option value="1">Afghanistan</option>
<option value="2">Albania</option>
<option value="3">Algeria</option>
<option value="4">Andorra</option>
<option value="5">Angola</option>
<option value="6">Antigua and Barbuda</option>
<option value="7">Argentina</option>
<option value="8">Armenia</option>
<option value="9">Australia</option>
<option value="10">Austria</option>
<option value="11">Azerbaijan</option>
<option value="12">Bahamas</option>
<option value="13">Bahrain</option>
<option value="14">Bangladesh</option>
<option value="15">Barbados</option>
<option value="16">Belarus</option>
<option value="17">Belgium</option>
<option value="18">Belize</option>
<option value="19">Benin</option>
<option value="20">Bhutan</option>
<option value="21">Bolivia</option>
<option value="22">Bosnia and Herzegovina</option>
<option value="23">Botswana</option>
<option value="24">Brazil</option>
<option value="25">Brunei</option>
<option value="26">Bulgaria</option>
<option value="27">Burkina Faso</option>
<option value="28">Burundi</option>
<option value="29">Cabo Verde</option>
<option value="30">Cambodia</option>
<option value="31">Cameroon</option>
<option value="32">Canada</option>
<option value="33">Central African Republic (CAR)</option>
<option value="34">Chad</option>
<option value="35">Chile</option>
<option value="36">China</option>
<option value="37">Colombia</option>
<option value="38">Comoros</option>
<option value="39">Congo, Democratic Republic of the</option>
<option value="40">Congo, Republic of the</option>
<option value="41">Costa Rica</option>
<option value="42">Cote d'Ivoire</option>
<option value="43">Croatia</option>
<option value="44">Cuba</option>
<option value="45">Cyprus</option>
<option value="46">Czechia</option>
<option value="47">Denmark</option>
<option value="48">Djibouti</option>
<option value="49">Dominica</option>
<option value="50">Dominican Republic</option>
<option value="51">Ecuador</option>
<option value="52">Egypt</option>
<option value="53">El Salvador</option>
<option value="54">Equatorial Guinea</option>
<option value="55">Eritrea</option>
<option value="56">Estonia</option>
<option value="57">Eswatini (formerly Swaziland)</option>
<option value="58">Ethiopia</option>
<option value="59">Fiji</option>
<option value="60">Finland</option>
<option value="61">France</option>
<option value="62">Gabon</option>
<option value="63">Gambia</option>
<option value="64">Georgia</option>
<option value="65">Germany</option>
<option value="66">Ghana</option>
<option value="67">Greece</option>
<option value="68">Grenada</option>
<option value="69">Guatemala</option>
<option value="70">Guinea</option>
<option value="71">Guinea-Bissau</option>
<option value="72">Guyana</option>
<option value="73">Haiti</option>
<option value="74">Honduras</option>
<option value="75">Hungary</option>
<option value="76">Iceland</option>
<option value="77">India</option>
<option value="78">Indonesia</option>
<option value="79">Iran</option>
<option value="80">Iraq</option>
<option value="81">Ireland</option>
<option value="82">Israel</option>
<option value="83">Italy</option>
<option value="84">Jamaica</option>
<option value="85">Japan</option>
<option value="86">Jordan</option>
<option value="87">Kazakhstan</option>
<option value="88">Kenya</option>
<option value="89">Kiribati</option>
<option value="90">Kosovo</option>
<option value="91">Kuwait</option>
<option value="92">Kyrgyzstan</option>
<option value="93">Laos</option>
<option value="94">Latvia</option>
<option value="95">Lebanon</option>
<option value="96">Lesotho</option>
<option value="97">Liberia</option>
<option value="98">Libya</option>
<option value="99">Liechtenstein</option>
<option value="100">Lithuania</option>
<option value="101">Luxembourg</option>
<option value="102">Madagascar</option>
<option value="103">Malawi</option>
<option value="104">Malaysia</option>
<option value="105">Maldives</option>
<option value="106">Mali</option>
<option value="107">Malta</option>
<option value="108">Marshall Islands</option>
<option value="109">Mauritania</option>
<option value="110">Mauritius</option>
<option value="111">Mexico</option>
<option value="112">Micronesia</option>
<option value="113">Moldova</option>
<option value="114">Monaco</option>
<option value="115">Mongolia</option>
<option value="116">Montenegro</option>
<option value="117">Morocco</option>
<option value="118">Mozambique</option>
<option value="119">Myanmar (formerly Burma)</option>
<option value="120">Namibia</option>
<option value="121">Nauru</option>
<option value="122">Nepal</option>
<option value="123">Netherlands</option>
<option value="124">New Zealand</option>
<option value="125">Nicaragua</option>
<option value="126">Niger</option>
<option value="127">Nigeria</option>
<option value="128">North Korea</option>
<option value="129">North Macedonia (formerly Macedonia)</option>
<option value="130">Norway</option>
<option value="131">Oman</option>
<option value="132">Pakistan</option>
<option value="133">Palau</option>
<option value="134">Palestine</option>
<option value="135">Panama</option>
<option value="136">Papua New Guinea</option>
<option value="137">Paraguay</option>
<option value="138">Peru</option>
<option value="139">Philippines</option>
<option value="140">Poland</option>
<option value="141">Portugal</option>
<option value="142">Qatar</option>
<option value="143">Romania</option>
<option value="144">Russia</option>
<option value="145">Rwanda</option>
<option value="146">Saint Kitts and Nevis</option>
<option value="147">Saint Lucia</option>
<option value="148">Saint Vincent and the Grenadines</option>
<option value="149">Samoa</option>
<option value="150">San Marino</option>
<option value="151">Sao Tome and Principe</option>
<option value="152">Saudi Arabia</option>
<option value="153">Senegal</option>
<option value="154">Serbia</option>
<option value="155">Seychelles</option>
<option value="156">Sierra Leone</option>
<option value="157">Singapore</option>
<option value="158">Slovakia</option>
<option value="159">Slovenia</option>
<option value="160">Solomon Islands</option>
<option value="161">Somalia</option>
<option value="162">South Africa</option>
<option value="163">South Korea</option>
<option value="164">South Sudan</option>
<option value="165">Spain</option>
<option value="166">Sri Lanka</option>
<option value="167">Sudan</option>
<option value="168">Suriname</option>
<option value="169">Sweden</option>
<option value="170">Switzerland</option>
<option value="171">Syria</option>
<option value="172">Taiwan</option>
<option value="173">Tajikistan</option>
<option value="174">Tanzania</option>
<option value="175">Thailand</option>
<option value="176">Timor-Leste</option>
<option value="177">Togo</option>
<option value="178">Tonga</option>
<option value="179">Trinidad and Tobago</option>
<option value="180">Tunisia</option>
<option value="181">Turkey</option>
<option value="182">Turkmenistan</option>
<option value="183">Tuvalu</option>
<option value="184">Uganda</option>
<option value="185">Ukraine</option>
<option value="186">United Arab Emirates (UAE)</option>
<option value="187">United Kingdom (UK)</option>
<option value="188">United States of America (USA)</option>
<option value="189">Uruguay</option>
<option value="190">Uzbekistan</option>
<option value="191">Vanuatu</option>
<option value="192">Vatican City (Holy See)</option>
<option value="193">Venezuela</option>
<option value="194">Vietnam</option>
<option value="195">Yemen</option>
<option value="196">Zambia</option>
<option value="197">Zimbabwe</option>